insert into community_groups (id, name, description, type, location, member_count)
values
  ('asu', 'Arizona State University', 'International student community for ASU.', 'School', 'Tempe, Arizona', 0),
  ('gcu', 'Grand Canyon University', 'International student community for GCU.', 'School', 'Phoenix, Arizona', 0),
  ('university-of-arizona', 'University of Arizona', 'International student community for University of Arizona.', 'School', 'Tucson, Arizona', 0),
  ('ut-austin', 'University of Texas at Austin', 'International student community for UT Austin.', 'School', 'Austin, Texas', 0),
  ('texas-am', 'Texas A&M University', 'International student community for Texas A&M.', 'School', 'College Station, Texas', 0),
  ('ucla', 'UCLA', 'International student community for UCLA.', 'School', 'Los Angeles, California', 0),
  ('usc', 'University of Southern California', 'International student community for USC.', 'School', 'Los Angeles, California', 0),
  ('uc-berkeley', 'UC Berkeley', 'International student community for UC Berkeley.', 'School', 'Berkeley, California', 0),
  ('stanford', 'Stanford University', 'International student community for Stanford.', 'School', 'Stanford, California', 0),
  ('nyu', 'New York University', 'International student community for NYU.', 'School', 'New York, New York', 0),
  ('columbia', 'Columbia University', 'International student community for Columbia.', 'School', 'New York, New York', 0),
  ('northeastern', 'Northeastern University', 'International student community for Northeastern.', 'School', 'Boston, Massachusetts', 0),
  ('boston-university', 'Boston University', 'International student community for BU.', 'School', 'Boston, Massachusetts', 0),
  ('uiuc', 'University of Illinois Urbana-Champaign', 'International student community for UIUC.', 'School', 'Urbana-Champaign, Illinois', 0),
  ('university-of-washington', 'University of Washington', 'International student community for UW.', 'School', 'Seattle, Washington', 0),
  ('georgia-tech', 'Georgia Tech', 'International student community for Georgia Tech.', 'School', 'Atlanta, Georgia', 0),
  ('university-of-michigan', 'University of Michigan', 'International student community for University of Michigan.', 'School', 'Ann Arbor, Michigan', 0),
  ('purdue', 'Purdue University', 'International student community for Purdue.', 'School', 'West Lafayette, Indiana', 0),
  ('university-of-florida', 'University of Florida', 'International student community for University of Florida.', 'School', 'Gainesville, Florida', 0),
  ('upenn', 'University of Pennsylvania', 'International student community for Penn.', 'School', 'Philadelphia, Pennsylvania', 0),
  ('phoenix', 'Phoenix', 'City group for international students and newcomers in Phoenix.', 'City', 'Arizona', 0),
  ('tempe', 'Tempe', 'City group for international students and newcomers in Tempe.', 'City', 'Arizona', 0),
  ('los-angeles', 'Los Angeles', 'City group for international students and newcomers in Los Angeles.', 'City', 'California', 0),
  ('san-francisco-bay-area', 'San Francisco Bay Area', 'City group for international students and newcomers in the Bay Area.', 'City', 'California', 0),
  ('new-york-city', 'New York City', 'City group for international students and newcomers in New York City.', 'City', 'New York', 0),
  ('boston', 'Boston', 'City group for international students and newcomers in Boston.', 'City', 'Massachusetts', 0),
  ('chicago', 'Chicago', 'City group for international students and newcomers in Chicago.', 'City', 'Illinois', 0),
  ('austin', 'Austin', 'City group for international students and newcomers in Austin.', 'City', 'Texas', 0),
  ('dallas-fort-worth', 'Dallas-Fort Worth', 'City group for international students and newcomers in DFW.', 'City', 'Texas', 0),
  ('houston', 'Houston', 'City group for international students and newcomers in Houston.', 'City', 'Texas', 0),
  ('seattle', 'Seattle', 'City group for international students and newcomers in Seattle.', 'City', 'Washington', 0),
  ('atlanta', 'Atlanta', 'City group for international students and newcomers in Atlanta.', 'City', 'Georgia', 0),
  ('miami', 'Miami', 'City group for international students and newcomers in Miami.', 'City', 'Florida', 0),
  ('washington-dc', 'Washington, DC', 'City group for international students and newcomers in Washington, DC.', 'City', 'District of Columbia', 0),
  ('san-diego', 'San Diego', 'City group for international students and newcomers in San Diego.', 'City', 'California', 0),
  ('denver', 'Denver', 'City group for international students and newcomers in Denver.', 'City', 'Colorado', 0)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  type = excluded.type,
  location = excluded.location;
